version: '3.9'

services:
  backend:
    build: ./backend
    image: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # TODO: Find a way to fix live reload for backend. 
    # Probably an unexpected situation with Docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/taskmanager
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: taskmanager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
